# Implementação Computacional

## Formulação do Problema do Caixeiro-Viajante - Naïve

Dado um conjunto  C = $\{c_1, c_2, c_3, ..., c_n \}$ de n cidades $c_i$, uma
matriz de distâncias entre as cidades $D$, onde $D_{ij}$ é a distância da cidade
$c_i \rightarrow c_j$, sendo que $D_{ij} = D_{ji}$  e $D_{ij} = \infty, i = j$, e o
conjunto de permutações entre as cidades $\pi$ onde $\pi$ tem tamanho $(n-1)! + 1$,
onde o + 1 significa a distância da última cidade com a cidade de origem. A
tarefa passa a ser encontrar o minímo da função objetivo definida como:

\begin{equation}
min\{ (\sum_{i=1}^n D\pi_i)_k \}
\end{equation} 

$k = 1,..., (n-1)! + 1$

#### Implementação do Problema do Caixeiro-Viajante - Naïve

```{cpp, echo = TRUE, eval = FALSE}
// [[depends(RcppEigen)]]
// [[depends(RcppNumerical)]]

#include <Rcpp.h>

using namespace Rcpp;

//[[Rcpp::export]]
DataFrame pcv_naivy(NumericMatrix x)
{
    // Vetor de inteiros para se referenciar a cada cidade
    IntegerVector int_cidades = seq_len(x.ncol()) - 1;
    CharacterVector char_cidades = as<CharacterVector>(int_cidades);

    // Garante que a primeira cidade é a origem
    IntegerVector rotas = seq_len(x.ncol()) - 1;
    rotas.erase(0);

    NumericVector custo;
    CharacterVector caminho;

    do
    {
        IntegerVector index = rotas;
        index.push_front(0);
        index.push_back(0);

        String it_caminho("0");
        double it_custo = 0;

        // cidades dentro do DO é a permutação da vez
        for (int i = 0; i < (index.size() - 1); i++)
        {
            double row = index[i];
            double col = index[i + 1];

            it_caminho += "-" + char_cidades[col];
            it_custo = it_custo + x(row, col);
        }

        caminho.push_back(it_caminho);
        custo.push_back(it_custo);

    } while (std::next_permutation(rotas.begin(), rotas.end()));

    // Seleciona os caminho com menor custo
    double menor_custo = min(custo);
    LogicalVector menor_rota_logical = (custo == menor_custo);
    IntegerVector menor_rota = seq_len(custo.length()) - 1;
    // Vetor com as possíveis cidades com menor custo
    menor_rota = menor_rota[menor_rota_logical];

    DataFrame df = DataFrame::create(
        Named("caminho") = caminho[menor_rota], 
        Named("custo") = custo[menor_rota]);
        
    return df;
}
```


## Formulação do Problema do Caixeiro-Viajante - Nearest Neighbor Method

Dado um conjunto  C = $\{c_1, c_2, c_3, ..., c_n \}$ de n cidades $c_i$, uma
matriz de distâncias entre as cidades $D$, onde $D_{ij}$ é a distância da
cidade $c_i \rightarrow c_j$, sendo que $D_{ij} = D_{ji}$  e $D_{ij} = \infty,
i = j$ o objetivo é encontrar a rota em que cada iteração tenha a menor
distância dentre todas até percorrer todas as cidades. 

Para cada iteração busca-se encontrar a cidade com a menor distância entre a 
cidade de origem e a de destino de modo que o algoritmo vai iterar n - 1 vezes.

### Implementação do Problema do Caixeiro-Viajante - Nearest Neighbor Method

```{cpp, echo = TRUE, eval = FALSE}
#include <Rcpp.h>

// [[depends(RcppEigen)]]
// [[depends(RcppNumerical)]]

using namespace Rcpp;

//[[Rcpp::export]]
DataFrame pcv_nearest_neighbor (NumericMatrix x) 
{

    NumericMatrix m(clone(x));

    // Vetor de inteiros para se referenciar a cada cidade
    IntegerVector int_cidade = seq_len(x.ncol()) - 1;
    // Vetor de inteiros para se referenciar as cidades não visitadas
    IntegerVector unvisited = seq_len(x.ncol()) - 1;
    // A cidade[0] é a origem
    unvisited.erase(0);
    // Sequência de cidades percorridas
    IntegerVector caminho;
    caminho.push_back(0);
    // Custo (Distância) percorrida
    double custo;

    NumericVector teste;

    while (true)
    {
        // Última cidade destino
        int origem = caminho[(caminho.length() - 1)];
        // Distâncias da origem para os destinos
        NumericVector destino = m(origem, _ ) ;
        // Vetor somente com as possíveis cidades (não visitadas)
        IntegerVector inf_cidades = setdiff(int_cidade, unvisited);

        // Para as cidades visitadas troca a distancia por infinito
        for (int i = 0; i < inf_cidades.length(); ++i)
        {
            // Rprintf("the value of inf_cidades[%i] : %f \n", i, inf_cidades[i]);
            destino[inf_cidades[i]] = R_PosInf;
        }

        // Menor distância
        double menor_distancia = min(destino);
        LogicalVector menor_distancia_logical = (destino == menor_distancia);
        IntegerVector cidade_destino = seq_len(destino.length())-1;
        // Vetor com as possíveis cidades com menor custo
        cidade_destino = cidade_destino[menor_distancia_logical];
        // Seleciona sempre a primeira cidade que aparecer com menor custo
        double custo_destino = m(origem, cidade_destino[0]);

        caminho.push_back(cidade_destino[0]);
        custo = custo + custo_destino;

        LogicalVector logical_unvisited = !(unvisited == cidade_destino[0]);
        unvisited = unvisited[logical_unvisited];

        if (unvisited.length() == 0)
        {
            break;
        }
    }

    // Liga o último destino com a origem
    int origem = caminho[(caminho.length() - 1)];
    double custo_destino = m(origem, 0);
    caminho.push_back(0);
    custo = custo + custo_destino;

    CharacterVector char_caminho = as<CharacterVector>(caminho);
    String concatena_caminho;

    // Concatena o caminho percorrido
    for (int i = 0; i < (char_caminho.size()); i++)
    {
        concatena_caminho += "-" + char_caminho[i];
    }
    concatena_caminho.replace_first("-", "");

    DataFrame df = DataFrame::create(
        Named("caminho") = concatena_caminho,
        Named("custo") = custo);

    return df;
}
```